### ISSUE TITLE
Velg meg!: Gjør bevisste valg i bruk av ressurser (kan være konseptuelt, men må være velbegrunnet)

### ISSUE THREAD

**Issue by pckv** [Safepath-AS/greentechsee-2024#46]
Gjør bevisste valg i bruk av ressurser (kan være konseptuelt, men må være velbegrunnet)

**Comment by Goransg** [comment]
Bærekraftsmessig

**Comment by Goransg** [comment]
Carpooling, sundbåt, gåing, elbil, gjenbruk av engangskopper, Laptop -> Mer energieffektiv enn stasjonær
